version: '3'
services:
  api:
    image: mailgenerator-express
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
